### ISSUE TITLE
`position` keeps growing even when stream is stopped

### ISSUE THREAD

**Issue by ChunMinChang** [mozilla/cubeb-coreaudio-rs#106]
[The failing test](https://treeherder.mozilla.org/logviewer.html#/jobs?job_id=310990910&repo=autoland&lineNumber=1803) in [BMO 1654699](https://bugzilla.mozilla.org/show_bug.cgi?id=1654699#c9) indicates the `position` keeps growing when stream is already stopped.

I guess the reason is that `interpolated_frames` is increased unlimitedly.

One approach is to add `outframes` to `OutputCallbackTimingData` and use it to create a bound for `interpolated_frames` (e.g., `interpolated_frames = min(interpolated_frames, outframes)`). Or we can apply the same manner on WASAPI backend for this case.

**Comment by padenot** [comment]
> One approach is to add `outframes` to `OutputCallbackTimingData` and use it to create a bound for `interpolated_frames` (e.g., `interpolated_frames = min(interpolated_frames, outframes)`). Or we can apply the same manner on WASAPI backend for this case.

https://lists.apple.com/archives/coreaudio-api/2005/Dec/msg00055.html says that this should be correct:

>  When AudioDeviceStop() is called on the IO thread, things are different. The HAL will not call the IOProc that was stopped again after the AudioDeviceStop() call completes, but the buffer provided by that IOProc will get played (and nothing after that from that IOProc).

The correct time is what you say. This also handles `cubeb_stream_stop`.

**Comment by padenot** [comment]
It's a bit hard to write a test for this. From the same email:

> From the HAL's perspective, AudioDeviceStop() has no guarantees unless it is called on the IO thread (that is, from inside of a call out to an IOProc). There could be any number of calls out to IOProcs between when the call to AudioDeviceStop() returns and when the the thread actually terminates. It's generally small, but it is definitely not guaranteed as the operation is totally asynchronous.

We do an early return in this case, so we shouldn't increment the clock, but we do anyways when interpolating (adding at most one buffer), so the previous patches in the series reorganize things so that the member that go into the `OutputCallbackTimingData` are not update in this case. 

However, we don't have the guarantee that the clock will stop incrementing after `stop` has been called (because it's going to interpolate), so we need to take this into account in the test.

> The only guarantee is that the HAL will send a notification for the property kAudioDevicePropertyDeviceIsRunning when things are totally done. (Note that in a process with many unrelated HAL clients, it's easy to get into a situation where calling AudioDeviceStop() only stops the IOProc in question and doesn't actually send a kAudioDevicePropertyDeviceIsRunning notification when other clients in the process are still doing IO.) 

We don't do this, but we make sure the user callback isn't called in this instance, and the linearization in other methods makes it safe.
